### ISSUE TITLE
Spatial conditioning 【render】

### ISSUE THREAD

**Issue by yytang25** [diffusion-face-relighting/difareli_code#11]
I really appreciate your work!
But I have a question, says the paper：

`Spatial conditioning. This technique is used for the light, shape, camera and background encodings (l, s, cam, bg). Given the face shape s, we first convert it to a triangle mesh using the three linear bases of FLAME model [27] and remove the ears, eyeballs, neck, and scalp from the mesh to retain only the face region (See Figure 2). `

<img width="503" alt="q" src="https://github.com/diffusion-face-relighting/difareli_code/assets/49153023/ecd79603-75b9-4f34-8132-aa0287716dc1">

But I can't find the corresponding implementation in the code. Can you tell me where it is? Because I ran the default code, the result was the whole portrait, not the face with a few attributes removed.

Thanks for your patience!

**Comment by XezXey** [comment]
Hi, thanks for interesting in our work. For masking the flame model, I've add the FLAME_masks_face-id.pkl that use in masking the face mesh out. Also, you can try to run this [script](https://github.com/diffusion-face-relighting/difareli_code/blob/main/experimental/masking_flame/mask_flame_for_difareli.ipynb) to see the removing of face meshes on specific regions. The implementations of masking flame model is at this [line](https://github.com/diffusion-face-relighting/difareli_code/blob/2dd24a024f26d659767df6ecc8da4ba47c55e7a8/preprocess_scripts/Relighting_preprocessing_tools/DECA/decalib/utils/renderer.py#L195).
