### ISSUE TITLE
missing python scripts for preprocessing

### ISSUE THREAD

**Issue by cleanBubble** [diffusion-face-relighting/difareli_code#2]
Great work and thank you for publishing the code!

I just wondered if you could upload the preprocessing scripts that are used in "create_dataset.py", which are "estimate_deca_for_dpm.py" and "gen_shadow.py"

Thank you!

**Comment by yytang25** [comment]
> Great work and thank you for publishing the code!
> 
> I just wondered if you could upload the preprocessing scripts that are used in "create_dataset.py", which are "estimate_deca_for_dpm.py" and "gen_shadow.py"
> 
> Thank you!

**Comment by yytang25** [comment]
> I encountered the same problem. Did you solve it?
> 
> Thank you!

**Comment by catherineytw** [comment]
I have the same problem, "estimate_deca_for_dpm.py" and "gen_shadow.py" are missing? Could you generously release them? 
Thank you!

**Comment by XezXey** [comment]
Sorry, it was my mistake. I've fixed the issue with this [commit](https://github.com/diffusion-face-relighting/difareli_code/commit/fa3750322c01929ccdecd51bb36acc00c89f792b).
