### ISSUE TITLE
FLAME_masks_face-id.pkl didn' found

### ISSUE THREAD

**Issue by zyhrainbow** [diffusion-face-relighting/difareli_code#3]
I met this problem "FileNotFoundError: [Errno 2] No such file or directory: '..../difareli_code/preprocess_scripts/Relighting_preprocessing_tools/DECA/script/../data//FLAME_masks_face-id.pkl'"
How can I solve it? thanks

**Comment by XezXey** [comment]
Due to the file size limit of github repos, I didn't upload all of the 3D template model files or checkpoints. You can find this while installing the DECA, or you can refers to the [offical page](https://flame.is.tue.mpg.de/) of Flame model.
