### ISSUE TITLE
The missing arcface weight file arcface/pretrained/BEST_checkpoint_r18.tar 

### ISSUE THREAD

**Issue by Johnx69** [diffusion-face-relighting/difareli_code#6]
Can you give me the pretrained file for the acrface module? @XezXey

**Comment by Johnx69** [comment]
Can you give me the pretrained file for the acrface module?

**Comment by Dengshunge** [comment]
https://github.com/foamliu/InsightFace-v2/releases/tag/v1.0

**Comment by Johnx69** [comment]
Thank you very much @Dengshunge !
