### ISSUE TITLE
missing guided-diffusion conf files

### ISSUE THREAD

**Issue by Dengshunge** [diffusion-face-relighting/difareli_code#7]
In `relight.py` file, the method of `get_cfg()` is  missing the configure files.  

![image](https://github.com/diffusion-face-relighting/difareli_code/assets/40339713/ee35b2fb-790f-4a44-b354-dbfde7376e1a)

**Comment by Dengshunge** [comment]
@XezXey

**Comment by Dengshunge** [comment]
Maybe the configure files in `../../config/**`?

**Comment by XezXey** [comment]
Yes, you need to change the path to match where your config folder located.
