### ISSUE TITLE
Weights to run DECA module

### ISSUE THREAD

**Issue by Johnx69** [diffusion-face-relighting/difareli_code#8]
Hello @XezXey, I saw that some weights file of FLAME are missing from the repo to run DECA. Can you upload it or give me instructions to reproduce them? 

They are 'DECA/data/generic_model.pkl', 'FLAME_masks_face-id.pkl' and 'FLAME_masks.pkl'

Thank you!

**Comment by YoucanBaby** [comment]
Hi @Johnx69 

I found 'FLAME_masks.pkl' in this link: "https://files.is.tue.mpg.de/tbolkart/FLAME/FLAME_masks.zip". But i didn't find 'FLAME_masks_face-id.pkl'. Have you found this model?

**Comment by XezXey** [comment]
I've upload the Flame_masks_face-id.pkl. for others, you can download from the [Flame](https://flame.is.tue.mpg.de/) website directly.

**Comment by lty2226262** [comment]
Hi XezXey, thanks for your great work. But I couldn't find Flame_masks_face-id.pkl from the link you provided https://github.com/diffusion-face-relighting/difareli_code/blob/main/sample_scripts/cond_utils/DECA/data/FLAME_masks_face-id.pkl
